//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaHm.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cards {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cards() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaHm.Server.Cards", typeof(Cards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _?  There&apos;s an app for that.
        ///Why can&apos;t I sleep at night?
        ///What&apos;s that smell?
        ///I got 99 problems but _ ain&apos;t one.
        ///Maybe she&apos;s born with it.  Maybe it&apos;s _.
        ///What&apos;s the next Happy Meal&amp;copy; toy?
        ///Anthropologists have recently discovered a primitive tribe that worships _.
        ///It&apos;s a pity that kids these days are all getting involved with _.
        ///During Picasso&apos;s often-overlooked Brown Period, he produced hundreds of paintings of _.
        ///Alternative medicine is now embracing the curative powers of _.
        ///And the Academy Aw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlackCards {
            get {
                return ResourceManager.GetString("BlackCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying sex snakes.
        ///Michelle Obama&apos;s arms.
        ///German dungeon porn.
        ///White people.
        ///Getting so angry that you pop a boner.
        ///Tasteful sideboob.
        ///Praying the gay away.
        ///Two midgets shitting into a bucket.
        ///MechaHitler.
        ///Being a motherfucking sorcerer.
        ///A disappointing birthday party.
        ///Puppies!
        ///A windmill full of corpses.
        ///Guys who don&apos;t call.
        ///Racially-biased SAT questions.
        ///Dying.
        ///Steven Hawking talking dirty.
        ///Being on fire.
        ///A lifetime of sadness.
        ///An erection that lasts longer than four hours.
        ///AIDS
        ///Same- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhiteCards {
            get {
                return ResourceManager.GetString("WhiteCards", resourceCulture);
            }
        }
    }
}
